- scripts/setup-ubuntu.sh
While creating a `Dockerfile` to evaluate [CI](https://github.com/substrait-io/substrait-cpp/issues/4#issuecomment-1364934929) approach, I found that it is better to include `wget` within the `scripts/setup-ubuntu.sh`.
> fix(library): added wget to dependencies in installation

- include/substrait/common/Exceptions.h
- include/substrait/function/Extension.h
- include/substrait/function/Function.h
- include/substrait/function/FunctionLookup.h
- include/substrait/function/FunctionSignature.h
- include/substrait/type/Type.h
- substrait/common/Exceptions.cpp
- substrait/function/Extension.cpp
- substrait/function/Function.cpp
- substrait/function/FunctionLookup.cpp
- substrait/function/tests/FunctionLookupTest.cpp
- substrait/type/Type.cpp
- substrait/type/tests/TypeTest.cpp
Rename namespace from 'substrait' to 'io::substrait' to avoid conflicts with namespace defined in substrait proto files.
> fix(naming):  Rename namespace 'substrait' to 'io::substrait'

- scripts/setup-ubuntu.sh
Needed in advance of #11 so that the continuous integration will pass.
> chore: Add the protobuf compiler package to the list of CI included packages.

- .github/workflows/build_test.yml
This should make it easier to determine the cause of CI failures.
> Add ctest option --output-on-failure

- include/substrait/common/Exceptions.h
- src/substrait/common/Exceptions.cpp
Substrait exceptions should note the code location of caller , see https://github.com/substrait-io/substrait-cpp/issues/27
>  Substrait exceptions should note the code location of caller

- .github/workflows/build_test.yml
- .licenserc.yaml
- scripts/setup-ubuntu.sh
- src/substrait/proto/update_proto_package.pl
- src/substrait/textplan/SymbolTable.cpp
Add lint to CI include checking for cmake-format, clang-format and license header, see https://github.com/substrait-io/substrait-cpp/issues/15
> Add lint to CI include checking for cmake-format, clang-format and license header

- src/substrait/textplan/converter/BasePlanProtoVisitor.cpp
The converter is tolerant of older plans so it needs to utilize the deprecated plan format to function properly.
> GH-41: Disable warnings about usage of deprecated args

- .gitmodules
- .licenserc.yaml
- include/substrait/expression/DecimalLiteral.h
- scripts/setup-ubuntu.sh
- src/substrait/CMakeLists.txt
- src/substrait/expression/CMakeLists.txt
- src/substrait/expression/DecimalLiteral.cpp
- src/substrait/expression/tests/CMakeLists.txt
- src/substrait/expression/tests/DecimalTest.cpp
- src/substrait/textplan/Location.cpp
- src/substrait/textplan/Location.h
- src/substrait/textplan/SubstraitErrorListener.cpp
- src/substrait/textplan/SubstraitErrorListener.h
- src/substrait/textplan/SymbolTable.cpp
- src/substrait/textplan/SymbolTable.h
- src/substrait/textplan/SymbolTablePrinter.cpp
- src/substrait/textplan/converter/CMakeLists.txt
- src/substrait/textplan/converter/InitialPlanProtoVisitor.cpp
- src/substrait/textplan/converter/InitialPlanProtoVisitor.h
- src/substrait/textplan/converter/PlanPrinterVisitor.cpp
- src/substrait/textplan/converter/PlanPrinterVisitor.h
- src/substrait/textplan/converter/Tool.cpp
- src/substrait/textplan/converter/tests/BinaryToTextPlanConversionTest.cpp
- src/substrait/textplan/tests/CMakeLists.txt
- src/substrait/textplan/tests/ParseResultMatchers.cpp
- src/substrait/textplan/tests/ParseResultMatchers.h
- third_party/CMakeLists.txt
* Adds support for functions
* Adds support for most literal types (including Decimal)
* Quality improvements
* Adds a new matcher that allows only symbols of a particular type to be matched
* Added PROTO_LOCATION macro to make specifying locations more convenient.
* Upgraded the converter tool to accept globs (only useful for testing as shells already expand globs).
* Many error messages are now returned to the ParseResult instead of being left in text for a human to detect.
> feat: functions and literals in text format

- src/substrait/textplan/RelationData.h
- src/substrait/textplan/converter/InitialPlanProtoVisitor.cpp
- src/substrait/textplan/converter/InitialPlanProtoVisitor.h
- src/substrait/textplan/converter/PlanPrinterVisitor.cpp
- src/substrait/textplan/converter/PlanPrinterVisitor.h
- src/substrait/textplan/converter/README.md
- src/substrait/textplan/converter/tests/BinaryToTextPlanConversionTest.cpp
* Implemented printing of the join relation.
* Now collects the schema for each relation in RelationData.
* Updated field references to be scoped as documented in the Substrait main repo.
* Added simple readme to explain how to use the plan converter tool.
> feat: join relation and proper function scoping

- src/substrait/textplan/converter/PlanPrinterVisitor.cpp
- src/substrait/textplan/converter/PlanPrinterVisitor.h
Complex expressions were difficult to read.  This PR adds a line break and indentation before every nested function reference which greatly improves readability in constructed text plans.
> feat: pretty printing of expressions

- src/substrait/type/Type.cpp
- src/substrait/type/tests/TypeTest.cpp
Previously a question mark anywhere within a type string would make a type nullable.  This PR corrects that calculation.
> fix: Correct nullable handling behavior for complex types

- src/substrait/textplan/converter/PlanPrinterVisitor.cpp
- src/substrait/textplan/tests/ParseResultMatchers.cpp
- src/substrait/textplan/tests/ParseResultMatchers.h
Now emits the first mismatch between the two strings to aid in determining what went wrong.
This PR also updates the parameter passing style used.
> feat:  Add first mismatch to EqSquashingWhitespace googletest matcher

- src/substrait/textplan/SymbolTablePrinter.cpp
- src/substrait/textplan/SymbolTablePrinter.h
- src/substrait/textplan/converter/BasePlanProtoVisitor.h
- src/substrait/textplan/converter/InitialPlanProtoVisitor.cpp
- src/substrait/textplan/converter/InitialPlanProtoVisitor.h
- src/substrait/textplan/converter/PlanPrinterVisitor.cpp
- src/substrait/textplan/parser/SubstraitPlanPipelineVisitor.cpp
- src/substrait/textplan/parser/SubstraitPlanRelationVisitor.cpp
- src/substrait/textplan/parser/SubstraitPlanRelationVisitor.h
- src/substrait/textplan/parser/SubstraitPlanVisitor.cpp
- src/substrait/textplan/parser/SubstraitPlanVisitor.h
- src/substrait/textplan/parser/grammar/SubstraitPlanLexer.g4
- src/substrait/textplan/parser/grammar/SubstraitPlanParser.g4
- src/substrait/textplan/parser/tests/TextPlanParserTest.cpp
- src/substrait/textplan/tests/ParseResultMatchers.cpp
- src/substrait/textplan/tests/ParseResultMatchers.h
* Relations are now interconnected as defined by pipelines.
* Expressions are now emitted to binary plans.
* HasErrors matcher now explains the difference in errors.
> feat: relations and expressions binary output for the textplan parser

- src/substrait/textplan/parser/SubstraitPlanRelationVisitor.cpp
- src/substrait/textplan/parser/grammar/SubstraitPlanParser.g4
- src/substrait/textplan/parser/tests/TextPlanParserTest.cpp
Now that the underlying type library doesn't segfault when given a map missing a key or value, properly detect such cases and return errors.
> fix: detect when maps are missing keys and/or values

- src/substrait/textplan/Location.cpp
- src/substrait/textplan/Location.h
- src/substrait/textplan/StructuredSymbolData.h
- src/substrait/textplan/converter/tests/BinaryToTextPlanConversionTest.cpp
- src/substrait/textplan/converter/tests/CMakeLists.txt
- src/substrait/textplan/parser/SubstraitPlanPipelineVisitor.cpp
- src/substrait/textplan/parser/SubstraitPlanRelationVisitor.cpp
- src/substrait/textplan/parser/SubstraitPlanRelationVisitor.h
- src/substrait/textplan/parser/SubstraitPlanVisitor.cpp
- src/substrait/textplan/parser/SubstraitPlanVisitor.h
- src/substrait/textplan/parser/data/provided_sample1.splan
- src/substrait/textplan/parser/grammar/SubstraitPlanParser.g4
- src/substrait/textplan/parser/tests/TextPlanParserTest.cpp
* Fields are now emitted in expressions completing expression handling.
* Schemas and sources are also now implemented.
* Removes projection as a relation detail in favor of expression for project relations.
> feat: fields, schemas, and sources binary output for the textplan parser

- src/substrait/textplan/SymbolTablePrinter.cpp
- src/substrait/textplan/converter/CMakeLists.txt
- src/substrait/textplan/converter/ReferenceNormalizer.cpp
- src/substrait/textplan/converter/ReferenceNormalizer.h
- src/substrait/textplan/converter/tests/BinaryToTextPlanConversionTest.cpp
- src/substrait/textplan/parser/tests/TextPlanParserTest.cpp
- src/substrait/textplan/tests/CMakeLists.txt
- src/substrait/textplan/tests/RoundtripTest.cpp
The normalizer orders the extension uri spaces and function extensions alphabetically (and renumbers accordingly) so that it is easier to compare binary plans.   A slight change to the existing sort behavior is made to be consistent with this ordering.
> feat: add binary plan normalizer

- src/substrait/textplan/converter/ReferenceNormalizer.cpp
As suggested by @bkietz this PR upgrades the sort routine to utilize tuple's built-in compare behavior.  This reduces the complexity of evaluating each set of four possibilities for each key manually.
> refactor:  upgrade multi-key sort

- .gitmodules
- CMakeLists.txt
- scripts/setup-ubuntu.sh
- src/substrait/common/CMakeLists.txt
- src/substrait/proto/CMakeLists.txt
- src/substrait/textplan/converter/LoadBinary.cpp
- src/substrait/textplan/parser/SubstraitPlanRelationVisitor.cpp
- src/substrait/textplan/tests/CMakeLists.txt
- src/substrait/textplan/tests/RoundtripTest.cpp
- third_party/CMakeLists.txt
The version numbering scheme for the protobuf compiler was updated which causes a mismatch warning to appear for versions of cmake less than 3.27.  Later versions of protobuf are bundled with their own copy of abseil.  Since protobuf always required abseil anyway, this fix also updates the code to rely on that (when available) instead of our own submodule.  This should lead to greater consistency (especially with new protobuf code leaning on an experimental logging feature that won't be available in older versions of abseil).  If the newer CONFIG-based method of findpackage does not work, we now fall back to the older method of using findpackage.  The version of cmake that we require is still 3.20 as 3.27 isn't available in enough locations to advance to that minimum.
> fix:  support both old and new versions of protobuf

- src/substrait/textplan/converter/CMakeLists.txt
- src/substrait/textplan/parser/CMakeLists.txt
- third_party/CMakeLists.txt
- third_party/datetime.cmake
By switching to an external dependency controlled by a central file we can more cleanly reference date::date and date::tz.  We could do the same by "externally loading" a submodule but either way we end up downloading the datetime repo.
> feat: switch datetime package to an external dependency

- .github/workflows/build_test.yml
- CMakeLists.txt
- export/planloader/CMakeLists.txt
Adds an explicit timeout and retry to ensure that we don't run too long (and can identify any tests that are getting stalled out).
> fix:  get CI working again

- export/planloader/tests/CMakeLists.txt
That variable was previously computed based on `CMAKE_SOURCE_DIR`, which is the wrong value if `substrait-cpp` is used as a dependency from a different top-level CMake project. The PR applies the pattern based on `CMAKE_CURRENT_SOURCE_DIR` used in other tests.
> fix: Set TEXTPLAN_SOURCE_DIR based on current dir in planloader test.

- CMakeLists.txt
- export/planloader/CMakeLists.txt
- src/substrait/CMakeLists.txt
- src/substrait/common/CMakeLists.txt
- src/substrait/expression/CMakeLists.txt
- src/substrait/function/CMakeLists.txt
- src/substrait/proto/CMakeLists.txt
- src/substrait/textplan/CMakeLists.txt
- src/substrait/textplan/converter/CMakeLists.txt
- src/substrait/textplan/parser/CMakeLists.txt
- src/substrait/textplan/parser/grammar/CMakeLists.txt
- src/substrait/type/CMakeLists.txt
- third_party/CMakeLists.txt
This allows to run `cmake --install .` to install the project to a
system such that it can be consumed with `find_package()`. This required
the following changes:
* Add `install(TARGET ...)` commands for all library and executable targets.
* Add all public header files to the `HEADER` `FILE_SET` of their respective target.
* Export all these targets to an export set and `install(EXPORT ...)` that export set.
* Provide install-time paths for several `target_include_directories()`,
some of which are empty because the headers are not installed.
Since some of the library targets depend on external projects (`abseil-cpp`
and `yaml-cpp`), the install logic of these projects also needs to be enabled.
This change is not only necessary to actually install the project, but
also to consume it via …
> feat: Make main target installable.

- third_party/antlr4/cmake/ExternalAntlr4Cpp.cmake
This PR adds the `-DCMAKE_CXX_COMPILER` flag to the CMake flags of the external project for ANTLR. Without that, the external project uses the system default, which may not be what the user wants (and even be broken).
> fix: Use CXX compiler of main project for ANTLR external project.

- src/substrait/proto/CMakeLists.txt
`protoc`'s `--proto_path` argument is expected to be provided multiple times if multiple directories are to be considered. Concatenating with `:` is invalid on some systems (Windows):
```sh
> protoc --help
-IPATH, --proto_path=PATH   Specify the directory in which to search for
imports.  May be specified multiple times;
directories will be searched in order.  If not
given, the current working directory is used.
If not found in any of the these directories,
the --descriptor_set_in descriptors will be
checked for required proto file.
```
> Don't concatenate paths in `--proto_path`

- src/substrait/textplan/parser/grammar/CMakeLists.txt
It isn't sufficient to rely on a single [`add_definitions`](https://github.com/substrait-io/substrait-cpp/blob/cc8d08af7a7ff4b65d0081fc18f9bb243fe85824/src/substrait/textplan/parser/grammar/CMakeLists.txt#L8) when defining this. Other things which pulls in ANTLR headers _must_ define this as well - if not, we end up with very hard to debug symbol visibility errors.
Set it as a public compile definition on the target to ensure the definition propagates.
> Set ANTLR4CPP_STATIC for everything that links against ANTLR

- third_party/CMakeLists.txt
Substrait-cpp is (i assume) intended to embed into other projects, so other subprojects should adhere to parent projects' settings. For GTest on windows, this requires that `gtest_force_shared_crt ` is enabled ([doc](https://github.com/google/googletest/blob/main/googletest/README.md)).
> Prevent gtest compiler/link errors on windows

- src/substrait/textplan/StructuredSymbolData.h
Holy moly this took a long time to debug.
MSVC gives absolutely zero warnings about if a struct/class is predeclared as one or the other, during compilation.
However, linking also needs to happen. And as it turns out, [whether a thing is a class or struct is part of the MSVC name mangling spec](https://en.wikiversity.org/wiki/Visual_C%2B%2B_name_mangling). Hence, we'd end up with e.g. this function (which references `SymbolInfo`) as being defined in it's object file as the following symbol:
> `lookupSymbolsByLocation@SymbolTable@textplan@substrait@io@@QEBA?AV?$vector@PEBUSymbolInfo@textplan@substrait@io@@V?$allocator@PEBUSymbolInfo@textplan@substrait@io@@@std@@@std@@AEBVLocation@234@@Z`
However, things which reference `SymbolInfo`, but which may have pulled in the incorrect predeclaration …
> Don't predeclare a struct as a class

- src/substrait/textplan/converter/BasePlanProtoVisitor.h
`visitPlan` is marked `protected`, meaning that non-subclasses of `BasePlanProtoVisitor` (which is probably what'll initiate the `visit` most of the time) cannot have access to the `visit` result.
Is there a specific reason that the traversal result has been hidden? If not, i suggest this change.
If so, subclasses are obviously free to implement a `visitWithResult` function to do the same thing.
> Don't throw away `visit` result in BasePlanProtoVisitor

- CMakeLists.txt
- src/substrait/common/CMakeLists.txt
As described in https://github.com/substrait-io/substrait-cpp/issues/116, the `io.h` file in this project conflicts with `io.h` of windows.
This fixes that (in the somewhat narrow compilation path that i'm exercising) by removing `include/substrait/common` from the include path, and instead relying on the (already existing) full include-path namespacing instead of relative includes of `io.h`.
> Fix namespace pollution on Windows

- include/substrait/expression/DecimalLiteral.h
int32_t, ... uses `<cstdint>`.
> Add missing include

- src/substrait/type/Type.cpp
The previous default template instances of `decodeType` for parametrized types used a "concatenation" on two char pointers, which doesn't work. This PR fixes that by making one of the two an `std::string`. The error did not show up until now because all supported types have specializations of the template.
> fix: use proper string concatenation for error on unsupported types

- export/planloader/CMakeLists.txt
- scripts/run-clang-tidy.sh
- scripts/setup-ubuntu.sh
- src/substrait/common/tests/IoTest.cpp
- src/substrait/textplan/converter/LoadBinary.cpp
- src/substrait/textplan/converter/ReferenceNormalizer.cpp
- src/substrait/textplan/parser/CMakeLists.txt
- src/substrait/textplan/tests/CMakeLists.txt
- src/substrait/textplan/tests/RoundtripTest.cpp
- third_party/protobuf.cmake
- use `!` instead of a `not` macro
- Don't build the `planparser` tool on windows; this uses unix commands to parse arguments.
- std::filesystem::path doesn't implicitly convert to std::string on msvc
- A shared library must specify export symbols (or set `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`) for a .lib file to be generated, which is required for things to link against said library.
- Can't use `*` (wildcard) on windows in a CMake command; use built-in CMake globbing instead.
- substrait-cpp tags an ancient version of protobuf (23.4) which itself uses an ancient version of abseil, that fails to build on MSVC. Bump protobuf to the newest version (28.2).
- various nitty changes related to the protobuf bump
Also requires https://github.com/EpsilonPrime/protobuf-matchers/pull/1/commits/91968ca85 …
> More windows-related fixes

- export/planloader/planloader.cpp
- export/planloader/planloader.h
- scripts/run-clang-format.sh
- scripts/setup-ubuntu.sh
Setting a fixed clang-format version should avoid confusion about nit-ty details in between clang-format versions. Pick 15; it should be available on all developer platforms, and is fairly recent.
> Re-format project + bump clang-format version

- third_party/protobuf.cmake
This PR adds compiler flags to the build process of the external dependencies downloaded and built via `FetchContent`, namely GTest and Protobuf. That build process generated more than 2k warnings in my system and, since those are well-tested external libraries, are almost certain all harmless.
> build: suppress warnings in external dependencies

- src/substrait/proto/CMakeLists.txt
- third_party/protobuf.cmake
This PR makes sure that all protobuf headers, either from the library or the generated ones, are marked as `SYSTEM` headers. This causes most compilers to include them via `-isystem` instead of `-I`, which, in turn, suppresses warnings from those headers and, thus, enables compiling the main project with `-Werror`.
This is achieved with the combination of several changes:
* Several unnecessary `include_directories` statements have been removed. These are unnecessary because we already depend on the `protobuf::libprotobuf` target, which includes header dependencies.
* We don't unnecessarily set the `target_include_directories` for the protobuf library headers for the same reason.
* We mark the Protobuf library downloaded by `FetchContent` as `SYSTEM`, which marks all targets in that …
> build: mark all protobuf headers as system headers
